name: FloatPlay
options:
  bundleIdPrefix: com.floatplay
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

targets:
  FloatPlay:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: ScreenOnScreen
    info:
      path: ScreenOnScreen/Info.plist
    entitlements:
      path: ScreenOnScreen/ScreenOnScreen.entitlements
    settings:
      base:
        PRODUCT_NAME: FloatPlay
        PRODUCT_BUNDLE_IDENTIFIER: com.floatplay.app
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: ScreenOnScreen/Info.plist
        CODE_SIGN_ENTITLEMENTS: ScreenOnScreen/ScreenOnScreen.entitlements
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_HARDENED_RUNTIME: YES
        GCC_OPTIMIZATION_LEVEL: s
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_OPTIMIZATION: space
